# A workflow that builds and (optionally) pushes the Docker container image
# artifacts for the application. The build action occurs on pull request events
# that target the `main` branch, and the push action occurs only with tagged releases
# and ticket branches.
---
name: "Build and Push"

"on":
  pull_request:
    branches:
      - main
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:

  build:
    name: "Build and Push Application Container Images"
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: lsst-sqre/build-and-push-to-ghcr@v1
        with:
          dockerfile: Dockerfile
          image: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
